### ISSUE TITLE
_version.py does not exist

### ISSUE THREAD

**Issue by pknag** [rcw-2/python-digikamdb#4]
I was looking for a python interface to digikamdb and this seems to fit the bill.
However, import fails since digikamdb/_version.py does not exist. It is imported in __init__.py
Probably a simple mistake.

**Comment by rcw-2** [comment]
_version.py is automatically generated during package build (the version is taken from tags), so it is not present in the raw source. You could do something like `python -m build -s` or `pip install -e .` to force generation.
Regards,
Ralph

**Comment by pknag** [comment]
Thanks. Learned something new. I see it is done by setuptools.
