### ISSUE TITLE
Running digikam-db when Digikam is opened?

### ISSUE THREAD

**Issue by rokdd** [rcw-2/python-digikamdb#6]
Another issue I was thinking about recently. Is it for the library important whether digikam is opened or closed? So when I write with python into the DB and Digikam is opened, which version will be written?

**Comment by rcw-2** [comment]
> Another issue I was thinking about recently. Is it for the library important whether digikam is opened or closed? So when I write with python into the DB and Digikam is opened, which version will be written?

My experience is that Digikam will not notice changes made by the library if the images were visited before (Digikam seems to cache database results). Digikam [advises against](https://docs.digikam.org/en/setup_application/database_settings.html#database-type-criteria) running multiple instances on the same database (though it is not clear to me if this covers a common _MySQL server_). I haven't tried changing the same data in both, but the results may be unpredictable.

**Comment by rokdd** [comment]
Thank you I would assume the same.. I will try to detect whether it is running
